### PR TITLE
Added links to navbar, made navbar relative so it shows on development pages

### LINKED ISSUE #93: Twelve of Code should appear on the navbar with release 1.0.0
### Issue Contents

With the official release of 1.0.0 on March 1, 2024, Twelve of Code should be added to the navbar.

### LINKED ISSUE #121: Change navbar references to be relative links instead of direct links
### Issue Contents

Due to cross-site scripting restrictions, the navbar will only show when you're viewing a page with the `mesure.x10.mx` domain. This is not ideal, as we need to be able to code stuff outside of that domain.

### PR DESCRIPTION
**Pull request by Mesure73L**
Resolves #121
Resolves #93

### CODE REVIEW

**Review by BeepBot99 — APPROVED** [review]
I'm not going to look at each file that you changed, but I trust you.
Merge when ready.

**Comment by BeepBot99** [comment]
Please do not add the `twelve of code` label unless you are actually changing code on the Twelve of Code website.

**Comment by Mesure73L** [comment]
> Please do not add the `twelve of code` label unless you are actually changing code on the Twelve of Code website.

It is still related to Twelve of Code, so I added the label.

**Comment by BeepBot99** [comment]
Just like before, you have asked me not to add the website labels if it doesn't directly change the content on those pages.

**Comment by BeepBot99** [comment]
**Merge when ready.**

**Comment by Mesure73L** [comment]
> Just like before, you have asked me not to add the website labels if it doesn't directly change the content on those pages.

That was when you added everything for something related to the repository. This is different.

**Comment by Mesure73L** [comment]
> **Merge when ready.**

IM TRYING TO BUT YOURE DISTRACTING ME

**Pull request merged**
