### PR TITLE
Added usage of CookieManager.__proto__.updateChallengeStatus() to example challenge

### LINKED ISSUE #146: Create example challenge using CookieManager class
### Issue Contents

It will be the challenge for November 1st, 2023.

### PR DESCRIPTION
**Pull request by BeepBot99**
Resolves #146.

### CODE REVIEW

**Comment by BeepBot99** [comment]
It's December 1st btw.

**Comment by Mesure73L** [comment]
bro just simplify the title name instead of ...ing it

**Comment by BeepBot99** [comment]
I didn't do the ..., it is automatic.

**Comment by Mesure73L** [comment]
well it still looks ugly

**Comment by BeepBot99** [comment]
IDFC what you think.

**Comment by BeepBot99** [comment]
By the way, check the name now.

**Comment by Mesure73L** [comment]
IDFC what you think.

**Comment by BeepBot99** [comment]
Just review this please you literally asked for it.

**Review by Mesure73L — CHANGES_REQUESTED** [review]
Use SWAL for it and anything else that I should use in the actual challenge, not just CMAN

**Comment by BeepBot99** [comment]
Okay, but `cman` is all you need to use. Swal2 is just optional for feedback, but is not required. Alternatively, if you want, I could make it so `cman.updateChallengeStatus()` always fires a Swal2 alert when called.

**Comment by Mesure73L** [comment]
I would like something to say "You completed the challenge!" or "That is not the correct answer." or something using SWAL2

**Comment by BeepBot99** [comment]
Just in the individual challenge or in `cman.updateChallengeStatus()`?

**Comment by Mesure73L** [comment]
Maybe add another argument to `cman.updateChallengeStatus()` for the message, its a success thing if the challenge is completed and error if it wasnt, and make it look like the data input

**Comment by BeepBot99** [comment]
What do you mean "make it look like the data input?"
Also, I think I'll just put it in the program, because `cman.updateChallengeStatus()` is only called when the status changes, but when you get it wrong twice in a row, it will not be called.

**Comment by Mesure73L** [comment]
> What do you mean "make it look like the data input?"

Make the SWAL2 style the same as the data input

> Also, I think I'll just put it in the program, because `cman.updateChallengeStatus()` is only called when the status changes, but when you get it wrong twice in a row, it will not be called.

What do you mean by the program? I want it to always run if the user gets it wrong.

**Comment by BeepBot99** [comment]
How could it not be the same as the data input?
And by the program, I mean the program that **this pull request is about you fucking idiot**.

**Comment by Mesure73L** [comment]
> How could it not be the same as the data input?

swal has different styles and options idiot

**Comment by Mesure73L** [comment]
> And by the program, I mean the program that **this pull request is about you very amazing person who I am appreciative of**.

Okay, thanks for the kind clarification!

**Comment by BeepBot99** [comment]
I'm the one that set up swal, not you. To use a different style, you would have to add another CDN reference to the `<head>`.

**Comment by BeepBot99** [comment]
> > And by the program, I mean the program that **this pull request is about you very horrible person who I am definitely not appreciative of**.
> 
> Okay, thanks for the kind clarification!

How is that kind?????

**Comment by Mesure73L** [comment]
> I'm the one that set up swal, not you. To use a different style, you would have to add another CDN reference to the `<head>`.

Okay, I did not know that, but yes you set it up that's why I don't know how things work. Also I also mean like the success or error thing in the data input, like in the corner and stuff not a modal in the center of the screen

**Comment by Mesure73L** [comment]
> > > And by the program, I mean the program that **this pull request is about you very horrible person who I am very appreciative of**.
> > 
> > 
> > Okay, thanks for the kind clarification!
> 
> How is that kind?????

How isn't it????????????????????????????????????

**Comment by Mesure73L** [comment]
Please do not become Aurify.
image
image
also why does it need to reload?

**Comment by BeepBot99** [comment]
Because when `cman.updateChallengeStatus()` is called, it automatically reloads.

**Comment by Mesure73L** [comment]
Then don't use updateChallengeStatus() unless it was successful

**Comment by BeepBot99** [comment]
Yes, but if it was unsucessful, I set it to in progress. Did you even read the code?

**Comment by Mesure73L** [comment]
If the answer was correct the challenge should never be marked as not completed, ever

**Comment by BeepBot99** [comment]
Yes, when is it?????

**Comment by BeepBot99** [comment]
To mark it as completed.

**Comment by Mesure73L** [comment]
SO WHY DOES IT NEED TO RELOAD IF IT WAS INCORRECT

**Comment by BeepBot99** [comment]
Because it's marking it as in progress.
# 🤯

**Comment by BeepBot99** [comment]
What is so confusing?

**Comment by Mesure73L** [comment]
> Because it's marking it as in progress.
> 
> # 🤯

don't mark it as in progress. thats for if its like a game or something where its not i/o. i/o should **always** be true or false

**Comment by BeepBot99** [comment]
No, it's in progress because it means you started attempting it but didn't finish yet. I am not changing it.

**Comment by Mesure73L** [comment]
Then I am changing it.

**Comment by BeepBot99** [comment]
Well then I'm not accepting this pull request.

**Review by Mesure73L — CHANGES_REQUESTED** [review]
Then I'm not accepting it either

**Comment by BeepBot99** [comment]
Okay, fine, I don't care, you're the one who asked for this.

**Comment by Mesure73L** [comment]
well I got the information I need from it, so im just gonna use it from the branch and not actually put it on 12oc

**Pull request closed without merging**
