### PR TITLE
Revert "Creating seedmanager class"

### PR DESCRIPTION
**Pull request by Mesure73L**
Please merge it into my branch instead of develop, I didn't realize there would be conflicts when trying to merge develop into my branch

### CODE REVIEW

**Comment by Mesure73L** [comment]
@BeepBot99

**Comment by Mesure73L** [comment]
Either do this or solve the conflicts

**Comment by BeepBot99** [comment]
I will just resolve the conflicts.

**Comment by BeepBot99** [comment]
@Mesure73L In the future, never unmerge a pull request that is needed. Just resolve the merge conflicts, it is not that hard if you only read the code and think logically.

**Pull request closed without merging**
