### PR TITLE
12oc execute JavaScript script on challenge load

### LINKED ISSUE #56: Creating challenges interface
### Issue Contents

Creating the logic that loads the challenges onto the page and executes them.
Note that for now, **challenge javascript code can be run in `script.js` because only @Mesure73L is writing them, but when custom challenges packs come out, it must move to another file.**

### PR DESCRIPTION
**Pull request by Mesure73L**
Resolves #56

### CODE REVIEW

**Comment by BeepBot99** [comment]
OK, I will review it later.

**Comment by Mesure73L** [comment]
You can delete the branch after this is merged.

**Comment by Mesure73L** [comment]
Please review as soon as possible.

**Review by BeepBot99 — APPROVED** [review]
LGTM

**Comment by Mesure73L** [comment]
> LGTM

?

**Comment by BeepBot99** [comment]
Looks good to me.

**Comment by BeepBot99** [comment]
Idiot

**Pull request merged**
