### PR TITLE
Create epoch timestamps for information.json statuses

### LINKED ISSUE #75: Need a plan for releasing challenges
### Issue Contents

Right now, we will have to manually go in and update `information.json`. Is there any better way to do this, that doesn't involve manually updating it?

### Steps

- [x] Think of a solution
- [x] Program that solution

### PR DESCRIPTION
**Pull request by BeepBot99**
Resolves #75.

### CODE REVIEW

**Comment by Mesure73L** [comment]
I will test it tomorrow.

**Comment by BeepBot99** [comment]
Note that, on this website for example, it is the **timestamp in miliseconds**, not the **epoch timestamp**. Although, they are both actually epoch timestamps since an epoch timestamp is just the time since the epoch, which was January 1, 1970 at 12 AM UTC.

**Comment by Mesure73L** [comment]
I was just about to ask that!

**Review by Mesure73L — APPROVED** [review]
LGTM!

**Comment by Mesure73L** [comment]
You can merge when ready

**Comment by BeepBot99** [comment]
> LGTM!

Wow with an exclamation mark!
But what did you do to test it?
Just curious.

**Comment by Mesure73L** [comment]
I tested with a timestamp in the past and in the future, and both `true` and `false`.

**Comment by BeepBot99** [comment]
But did you test it for years, months, and challenges?

**Comment by Mesure73L** [comment]
Months and challenges, probably will work in years also

**Pull request merged**
