### PR TITLE
Added mobile page for Twelve of Code

### LINKED ISSUE #40: Make 12oC Mobile Responsive
### What problem were you having?

It's not mobile responsive

### What solution would you like?

Make it mobile responsive

### What alternatives have you considered?

Be a dickhead

### What are some pros and cons of doing this?

Pros: everything
Cons: nothing

### What page is this for?

Twelve of Code

### PR DESCRIPTION
**Pull request by BeepBot99**
Resolves #40.

### CODE REVIEW

**Comment by Mesure73L** [comment]
I’ll review it later

**Comment by BeepBot99** [comment]
Okay, thank you.

**Comment by BeepBot99** [comment]
@Mesure73L Can you please review this now?

**Review by Mesure73L — CHANGES_REQUESTED** [review]
- Unformat "to merge it"
image
- Change my link on this to [my Carrd page](https://mesure.carrd.co)
image
- Don't lie /j
image

**Review by Mesure73L — APPROVED** [review]
LGTM (abbreviation):
Looks Good To Me
Often used in: Programming, collaboration
Similar: Okay, Looks good, Merge when ready

**Comment by BeepBot99** [comment]
You're saying that you're a stupid fucking idiot?????

**Comment by Mesure73L** [comment]
> You're saying that you're a stupid fucking idiot?????

When did I say that?

**Comment by BeepBot99** [comment]
A screenshot
Right here you stupid fucking idiot.

**Comment by Mesure73L** [comment]
> A screenshot
> Right here you stupid fucking idiot.

I can clearly see “Edited by BeepBot99” in that screenshot.

**Comment by Mesure73L** [comment]
Another screenshot
Please only edit messages when it’s necessary.

**Pull request merged**
