### PR TITLE
12oc hashtag url navigation

### LINKED ISSUE #32: 12oC challenge selector keeps challenge active after making the month unset
### What happened?

I clicked 2023 for the year, December for the month, and then Challenge 2 (although I don't think any of those selections matter, that's just what I chose).

Nothing was wrong until I clicked December again to disable it, and then I clicked it a third time. Challenge 2 was still appearing active even though it shouldn't be. (The challenge itself didn't appear, but the button was still appearing as active. Also, the JavaScript knew it shouldn't be active, just a visual glitch that should be fixed.)

### What did you expect to happen?

I expected the challenge to not be appearing as active, because it wasn't active and shouldn't be active.

### What page was this on?

twelve of code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

### Enter logs

_No response_

### Other notes

I'll give screenshots of what I did.

image
image
image
image
image
image

### LINKED ISSUE #64: Create hashes for 12oC challenges
### What problem were you having?

_No response_

### What solution would you like?

A way to put like `#2023-dec-1` at the end of the URL to open the page on that challenge would be nice.

### What alternatives have you considered?

`?challenge=20231201` or something (2023, 12, 01)

#### Pros
- Easier to share challenges that you enjoyed
- Faster to load onto a challenge

#### Cons
- IDK

### What page is this for?

Twelve of Code

### What needs to get done?

- [x] Automatically set the challenge to be active and load it on page load
- [x] Change the URL when a challenge is loaded
- [x] Detect when the URL is changed to allow users to type in the URL
- [x] Verify that the challenge is released and existent when attempting to load it
- [ ] Fix all bugs
- [ ] Add Wiki docs explaining how to use it (not required for completion)

### LINKED ISSUE #78: Challenge doesn't disappear after changing year
### What happened?

I selected the year, month, and challenge, and then I changed the year from 2023 to 2024. Everything worked as expected, except the challenge did not disappear.

### What did you expect to happen?

I expected the challenge to disappear.

### What page was this on?

Twelve of Code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

### Enter logs

_No response_

### Other notes

I'll include some screenshots.

image
image

### PR DESCRIPTION
**Pull request by BeepBot99**
Resolves #64
Resolves #78

### CODE REVIEW

**Comment by BeepBot99** [comment]
Good, all bugs fixed, except that the hash `#2023-jan` doesn't work as expected.

**Comment by Mesure73L** [comment]
> However, `#2023-jan` still doesn't work as expected.

I will look into that later

**Comment by Mesure73L** [comment]
`#2023-jan-1` does work as expected.

**Comment by Mesure73L** [comment]
@BeepBot99 Please review this as soon as possible.

**Comment by BeepBot99** [comment]
> `#2023-jan` does work as expected.

Are you sure you pushed to `origin` in the `12oc-hashtag-url-navigation` branch? This is what is in the code currently:
image
When the hash `#2023-jan` is used, this is the result:
image
The expected result would be for the hash to be automatically changed to `#2023` and this to be shown:
image

**Comment by Mesure73L** [comment]
Yes, I did push to origin, however you broke it.

**Comment by Mesure73L** [comment]
**DO NOT EDIT THIS.**

**Comment by BeepBot99** [comment]
> Yes, I did push to origin, however you broke it.

When, I did not. You can see I merged the `develop` branch into this branch. LOOK AT THE COMMIT. ALL I WAS CHANGING WAS RESOLVING THE CONFLICTS IN THE `script.js`. Look at what files I changed.

**Comment by BeepBot99** [comment]
Please stop blaming me for things that I did not do without any evidence.

**Comment by BeepBot99** [comment]
This looks good.
I can't review it because I made the pull request.
However, in the future, please do these two things:
* Don't blame me for anything without evidence. Look at the commit history. I did not do anything.
* Mark the pull request as `Ready for Review` when it is done.

**Comment by BeepBot99** [comment]
I am going to remove an empty line from the `README.md` so you are able to review it.

**Comment by Mesure73L** [comment]
Look. This is the commit where you broke it.
image

**Comment by Mesure73L** [comment]
My unsynced codespace worked with the feature until I synced it. I did not edit this outside of the codespace.

**Comment by Mesure73L** [comment]
I very much do have proof.

**Comment by BeepBot99** [comment]
Yeah. Two days ago. You said you did this yesterday.

**Comment by Mesure73L** [comment]
That line that you removed was the exact line that I needed to patch that bug. You deleted it.

**Comment by Mesure73L** [comment]
> > My unsynced codespace worked with the feature until I synced it.
> 
> Exactly, when you synced, it you pulled and pushed instead of pushing. Just pushing should be the default option, but if it isn't, click the drop down arrow next to the sync button and select the option to only push and overwrite.

It did not upload anything to GitHub. All commits I made were already pushed to origin.

**Comment by BeepBot99** [comment]
What do you mean they were already synced to the origin?
I never said you uploaded them.
When you make a commit in the codespace, these things happen:
1. It pulls the origin to the codespace
2. It pushes the codespaces to the origin

Instead of that, you have to just do step 2.

**Comment by Mesure73L** [comment]
Okay, so here's what happened:
On Thursday or Friday I fixed that bug, by adding that line.
2 days ago (Saturday) you removed that line.
I undid all of your commits and that fixed the issue.
**You broke it and I have proof.**

**Comment by BeepBot99** [comment]
Wasn't Saturday when we vced?

**Comment by Mesure73L** [comment]
We VCed on Friday.

**Comment by BeepBot99** [comment]
In addition, please never blame anyone no matter what. It does not create a constructive environment, and it doesn't help in any way.

**Comment by Mesure73L** [comment]
> In addition, please never blame anyone no matter what. It does not create a constructive environment, and it doesn't help in any way.

I was just pointing out that I already fixed it. I was not trying to argue. You started arguing.

**Comment by Mesure73L** [comment]
In the future, please do not edit a branch that I created unless I tell you to and **only for that exact thing.**

**Comment by BeepBot99** [comment]
No, remember, on Friday, when there was the merge conflict that we couldn't fix without breaking it, you asked me to fix it? I did not know that the one line I removed (which I had written in the first place a month ago) would relate at all to what you were doing. Furthermore, you are blaming me. I just want to let you know so that you don't do it in the future.

**Comment by Mesure73L** [comment]
> No, remember, on Friday, when there was the merge conflict that we couldn't fix without breaking it, you asked me to fix it?

What do you mean, when did I say that, and what was the merge conflict?

>  I did not know that the one line I removed (which I had written in the first place a month ago) would relate at all to what you were doing.

That line was not there before. I added it because it helped make the hash system easier to code.

>  Furthermore, you are blaming me. I just want to let you know so that you don't do it in the future.

I am not blaming you in a bad way. I just want to let you know so that you don't do it in the future.

**Comment by BeepBot99** [comment]
You need to review it first.

**Comment by Mesure73L** [comment]
Once I review it, can it be merged? This is technically you who's supposed to review this but since you created the PR you can't review it.

**Comment by BeepBot99** [comment]
Yes, it can, I already said that.

**Review by Mesure73L — DISMISSED** [review]
I don't remember you saying that but whatever, I'll resolve conflicts and merge it

**Comment by BeepBot99** [comment]
For script.js, keep this version.

**Comment by Mesure73L** [comment]
> For script.js, keep this version.

k

**Comment by BeepBot99** [comment]
In addition, some of the conflicts need a combined version of both. Do one of these two things:
* I resolve the conflicts
* We VC sometime and resolve the conflicts together

**Comment by BeepBot99** [comment]
Which one would you like to do?

**Comment by Mesure73L** [comment]
I would prefer to VC and work through it together, you pretending you don't know anything about it. That way I can learn and practice resolving conflicts so I can do it by myself in the future.

**Comment by Mesure73L** [comment]
I can vacuum cleaner tomorrow at -8:00.

**Comment by BeepBot99** [comment]
Is that supposed to be **-**8:00?

**Comment by BeepBot99** [comment]
> I would prefer to vacuum cleaner and work through it together, you pretending you don't know anything about it. That way I can learn and practice resolving conflicts so I can do it by myself in the future.

Okay.

**Comment by Mesure73L** [comment]
> Is that supposed to be **-** 8:00?

Yes, the `-` is a negative sign.

**Comment by BeepBot99** [comment]
> > Is that supposed to be **-** 8:00?
> 
> Yes, the `-` is a negative sign.

Does that mean 16:00 then? Because if so, then no, I can't.

**Comment by Mesure73L** [comment]
Can you vacuum cleaner on Thursday at -30:195?

**Comment by Mesure73L** [comment]
Can you vacuum cleaner on Thursday at -54:195?

**Comment by BeepBot99** [comment]
> Can you vacuum cleaner on Thursday at -54:195? (i hope thats correct lol)

Not until you tell me the correct time.

**Comment by Mesure73L** [comment]
> > Can you vacuum cleaner on Thursday at -54:195? (i hope thats correct lol)
> 
> Not until you tell me the correct time.

Can you visual communicator at 21:15ish?

**Comment by BeepBot99** [comment]
> > > Can you vacuum cleaner on Thursday at -54:195? (i hope thats correct lol)
> > 
> > 
> > Not until you tell me the correct time.
> 
> Can you visual communicator at 21:15ish?

Sure.

**Review by Mesure73L — APPROVED** [review]
Too lazy to actually review it rn but I'll trust you

**Pull request merged**
