### PR TITLE
Center challenges and remove empty space by license

### LINKED ISSUE #124: Remove the space in the Twelve of Code license
### Issue Contents

image

### PR DESCRIPTION
**Pull request by BeepBot99**
Resolves #124
Resolves #126

### CODE REVIEW

**Comment by Mesure73L** [comment]
Just letting you know, closing keywords only work when merging into `main`. (Found this out the hard way)

**Comment by BeepBot99** [comment]
Oh, good to know. I added the issues manually now.

**Comment by Mesure73L** [comment]
I'm pretty sure those also don't work

**Comment by BeepBot99** [comment]
Yes they do, I've done it before.

**Comment by Mesure73L** [comment]
The previous times I've done that I've had to manually close the issues.

**Comment by BeepBot99** [comment]
Okay, we'll see then.

**Comment by BeepBot99** [comment]
Can you just please review it?

**Comment by Mesure73L** [comment]
I will review it at 1238579234:435392709358012 today. /j

**Comment by BeepBot99** [comment]
Remember, there is always the deploy preview, so you don't have to open a codespace.

**Review by Mesure73L — APPROVED** [review]
8/10, would recommend to friends & family

8/10 speed
5/10 communication
10/10 quality

oh wait this is a code review right

Looks good™

**Comment by Mesure73L** [comment]
@BeepBot99 the issues did not close

**Pull request merged**
