### PR TITLE
Create data import and export

### LINKED ISSUE #15: Twelve of Code data input doesn't work
Mostly just a to-do but the Twelve of Code data input is disabled and needs to be programmed
image

- [x] Get Export Data working
- [x] Get Import Data working

### PR DESCRIPTION
**Pull request by BeepBot99**
Resolves #15. (One of the oldest issues yay.)

### CODE REVIEW

**Comment by BeepBot99** [comment]
@Mesure73L Do the hover effects on the buttons look good to you?

**Review by Mesure73L — APPROVED** [review]
LGTM, if you can make it go center out on hover and opposite for off hover that would be nice, but you can merge

**Comment by BeepBot99** [comment]
No don't review it it's a draft.

**Comment by BeepBot99** [comment]
> LGTM, if you can make it go center out on hover and opposite for off hover that would be nice, but you can merge

What do you mean?

**Comment by BeepBot99** [comment]
@Mesure73L Can I please have your **opinion** on the new hover effect?

**Comment by BeepBot99** [comment]
@Mesure73L Can you please review this today?

**Comment by BeepBot99** [comment]
What if I changed `twelve-of-code-export.txt` to `twelve-of-code-export-data.txt` or `twelve-of-code-data.txt`? Would that be better?

**Comment by Mesure73L** [comment]
Reviewing this RN

**Review by Mesure73L — CHANGES_REQUESTED** [review]
Suggestions:

1. Make the X button on the import data modal act as a cancel button to fix [this](https://files.catbox.moe/zlg086.mp4) problem.
2. Add a `#settings` hash to make it not close the settings tab on data reload.
3. Check the data with `information.json` to prevent [this problem](https://files.catbox.moe/nshxja.mp4).

> What if I changed `twelve-of-code-export.txt` to `twelve-of-code-export-data.txt` or `twelve-of-code-data.txt`? Would that be better?

Yes, use `twelve-of-code-data`.

**Comment by BeepBot99** [comment]
> * Make the X button on the import data modal act as a cancel button to fix [this](https://files.catbox.moe/zlg086.mp4) problem.

I tried that, I don't exactly know how to do it, but I can try again.

> * Add a `#settings` hash to make it not close the settings tab on data reload.

Okay.

> 3\. Check the data with `information.json` to prevent [this problem](https://files.catbox.moe/nshxja.mp4).

Oh, I thought I had already fixed that. I will do it again.



> Yes, use `twelve-of-code-data`.

Isn't that the first thing I had suggested?????

**Comment by Mesure73L** [comment]
What is the `Changed something` commit?

**Comment by BeepBot99** [comment]
IDK look at it.

**Comment by BeepBot99** [comment]
Oh right yeah it's important.

**Comment by BeepBot99** [comment]
Actually please **don't merge this yet** I want to change something.

**Comment by Mesure73L** [comment]
> IDK look at it.

That's why you should be more clear with commit names

**Comment by BeepBot99** [comment]
Okay actually it's fine. It could be slightly cleaner by changing that last commit, but it doesn't actually significantly affect anything.

**Review by Mesure73L — CHANGES_REQUESTED** [review]
Please check the input with `information.json` and **don't allow the user to input invalid years or months**. I changed `2023` to `2020` in my decoded data export, and it reloaded successfully but then I exported the data and this was my data: `{"completed":{"2024":{},"2025":{},"2026":{}},"user":{"username":"User-5113017104","seed":9468457691}}`

**Comment by Mesure73L** [comment]
Where did 2023 go?

**Comment by BeepBot99** [comment]
It wasn't in the data that was entered. But, when any request for it is made, it will be added.

**Comment by Mesure73L** [comment]
ohhh thats why i said that but makes sense

**Review by Mesure73L — APPROVED** [review]
LG™

**Comment by Mesure73L** [comment]
@BeepBot99 merge when 🟥y

**Pull request merged**
