### PR TITLE
Update netlify-twelve-of-code.yml

### PR DESCRIPTION
**Pull request by BeepBot99**
I don't think this really matters because the action still works but it is giving an error so this should fix it.

### CODE REVIEW

**Comment by Mesure73L** [comment]
Can you just remove it? its blocked for you or something and i have ghcs so yeah theres not really any point

**Comment by BeepBot99** [comment]
No it's not actually blocked, I use it.

**Comment by BeepBot99** [comment]
They unblocked it for some reason. (They have unblocked a lot of things recently.)
Also, even when it was blocked, it was only specific subdomains, but since the preview is different each time, it didn't block new previews.

**Comment by Mesure73L** [comment]
Then can we make it for all sites instead of just Twelve of Code?

**Review by Mesure73L — APPROVED** [review]
I'll accept this for now but we should set up all sites sometime after 1.0.0

**Comment by BeepBot99** [comment]
Sure, sometime when there is time to do it.

**Comment by Mesure73L** [comment]
OK

**Pull request merged**
