### PR TITLE
Added prefilled value to pros and cons in FR issue template

### LINKED ISSUE #104: Change "What are some pros and cons of doing this?" to two seperate questions
### What problem were you having?

In the Feature Request Issue Template, it has one question for both pros and cons.

### What solution would you like?

Add two seperate questions, one being "What are some pros of doing this?" and the other being "What are some cons of doing this?"

### What alternatives have you considered?

*No response*

### What are some pros and cons of doing this?

wait-

#### Pros:
- Easier to answer
- Looks better

#### Cons:
- Another question to answer

### Preview of how it would look after submission:

image

### What page is this for?

Repository

### PR DESCRIPTION
**Pull request by Mesure73L**
Resolves #104

### CODE REVIEW

**Comment by Mesure73L** [comment]
This is ready to be merged.

**Comment by BeepBot99** [comment]
Why are there so many empty lines in the new issue template?

**Comment by Mesure73L** [comment]
> Why are there so many empty lines in the new issue template?

YAML does not support `\n`, the way to do it is new lines.

**Comment by Mesure73L** [comment]
Actually don't merge it yet, I need to change one more thing first.

**Comment by Mesure73L** [comment]
Ready to be reviewed and merged.

**Review by BeepBot99 — APPROVED** [review]
Looks good.

**Pull request merged**
