### PR TITLE
Console clicker project

### PR DESCRIPTION
**Pull request by Mesure73L**

### CODE REVIEW

**Comment by BeepBot99** [comment]
What is this?

**Comment by BeepBot99** [comment]
Is this for the projects subdomain?

**Comment by BeepBot99** [comment]
Why are there other projects that are in the folder but not on the main projects site?

**Comment by BeepBot99** [comment]
By the way, in the future, please always merge into `develop` first **no matter what**.

**Comment by BeepBot99** [comment]
And, why does it not say what commands will do anything?

**Comment by BeepBot99** [comment]
And also, where do you click?

**Comment by BeepBot99** [comment]
>
```js
function addText(textInput, colorInput) {
    const span = document.createElement("span");
    const text = document.createTextNode(textInput);
    span.style.color = colorInput;
    span.appendChild(text);
    line.appendChild(span);
}
```

Okay, so just for in the future, you don't need to create a text node unless you have multiple. Otherwise, you can just do `span.innerText = `.

**Comment by Mesure73L** [comment]
> Why are there other projects that are in the folder but not on the main projects site?

too lazy to add them

> By the way, in the future, please always merge into `develop` first **no matter what**.

theres in progress 12oc stuff on develop, i want it in main now without 12oc, i can merge it into whatever i want

> And, why does it not say what commands will do anything?

im gonna make a wiki page

> And also, where do you click?

**Step 1: Locate your Keyboard**
A keyboard is the thing that you type letters on. The specific look and layout of the keyboard may differ, but it will look something like this:
image

**Step 2: Locate your Finger**
Your finger is the thing that you are able to type with. It may differ, but it will look something like this:
image

**Step 3: Find the Enter Key**
The enter key says "Enter," "Return," or might be a symbol. It is typically on the right side, near the middle (vertically).

**Step 4: Press the Enter Key**
Take your finger, place it on your keyboard, find the enter key, and press down.

You're done!

**Comment by BeepBot99** [comment]
No, I mean it doesn't say that you have to click enter.

**Comment by BeepBot99** [comment]
IDIOT.

**Comment by Mesure73L** [comment]
> No, I mean it doesn't say that you have to click enter.

too bad

**Pull request merged**
