### PR TITLE
12oC hash for URL navigation

### LINKED ISSUE #64: Create hashes for 12oC challenges
### What problem were you having?

_No response_

### What solution would you like?

A way to put like `#2023-dec-1` at the end of the URL to open the page on that challenge would be nice.

### What alternatives have you considered?

`?challenge=20231201` or something (2023, 12, 01)

#### Pros
- Easier to share challenges that you enjoyed
- Faster to load onto a challenge

#### Cons
- IDK

### What page is this for?

Twelve of Code

### What needs to get done?

- [x] Automatically set the challenge to be active and load it on page load
- [x] Change the URL when a challenge is loaded
- [x] Detect when the URL is changed to allow users to type in the URL
- [x] Verify that the challenge is released and existent when attempting to load it
- [ ] Fix all bugs
- [ ] Add Wiki docs explaining how to use it (not required for completion)

### LINKED ISSUE #78: Challenge doesn't disappear after changing year
### What happened?

I selected the year, month, and challenge, and then I changed the year from 2023 to 2024. Everything worked as expected, except the challenge did not disappear.

### What did you expect to happen?

I expected the challenge to disappear.

### What page was this on?

Twelve of Code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

### Enter logs

_No response_

### Other notes

I'll include some screenshots.

image
image

### PR DESCRIPTION
**Pull request by Mesure73L**
Resolves #64 
Resolves #78

### CODE REVIEW

**Comment by Mesure73L** [comment]
Ready to merge if it looks good

**Comment by Mesure73L** [comment]
By the way, the format for the hash is `#year-month-challenge`
Example: `#2023-dec-1`
If something is invalid, it should remove it and whatever comes after.

**Comment by BeepBot99** [comment]
Imagine not knowing how to spell exist**e**nt.

**Comment by BeepBot99** [comment]
Just curious, why are there 2023 november challenges?

**Comment by Mesure73L** [comment]
> Imagine not knowing how to spell exist**e**nt.

Timeout when I get home

> Why are there 2023 november challenges?

For testing with multiple months

**Comment by BeepBot99** [comment]
Sure time me out when you get home.
I probably won't be home until a few hours after that.
In addition, I will be invisible the whole time so you don't know.

**Review by BeepBot99 — COMMENTED** [review]
I will review this when I get home.

**Comment by Mesure73L** [comment]
Please don't leave a review to say you'll review it later. Just leave a comment.

**Comment by Mesure73L** [comment]
The branch can be deleted after merging.

**Comment by BeepBot99** [comment]
You can remove your assignment if you want, but the reason I assigned you is because you made it, and if I want any changes made, you would be the one to do it.

**Review by BeepBot99 — CHANGES_REQUESTED** [review]
If you type in the hash `#2023-idk`, it redirects you to `#2023`, but if you type in `#2023-novs`, or anything that starts with a month, it does not redirect. That behavior should be changed.

**Comment by Mesure73L** [comment]
Okay, I will change that.

**Review by BeepBot99 — CHANGES_REQUESTED** [review]
Please add this code after setting the hash:
```js
if (window.location.hash === "") {
    history.replaceState(null, null, window.location.pathname + window.location.search);
}
```

**Review by BeepBot99 — APPROVED** [review]

**Pull request merged**
