### PR TITLE
Made twelve of code Netlify action only apply to pull requests with the twelve of code label

### PR DESCRIPTION
**Pull request by BeepBot99**

### CODE REVIEW

**Comment by BeepBot99** [comment]
@Mesure73L Do these steps:
1. Delete the required action in the branch protection rule
2. Accept and merge this pull request
3. Merge `BeepBot99-patch-1` into `develop`
4. Add the branch protection rule back

**Comment by BeepBot99** [comment]
You might also need to update the site id if it's changed at all.

**Comment by Mesure73L** [comment]
Do I just check this checkbox or do something else?
image

**Comment by Mesure73L** [comment]
By the way, are we still gonna set up the previews for the other site pages?

**Comment by BeepBot99** [comment]
> Do I just check this checkbox or do something else?

You click the x next to the Netlify action and click save at the bottom of the page.
Then, you do steps 2 and 3 in my previous response, and then add `netlify/m73l-twelve-of-code-dev/deploy-preview` back.

**Comment by BeepBot99** [comment]
> By the way, are we still gonna set up the previews for the other site pages?

Yes, eventually.

**Comment by BeepBot99** [comment]
Actually, I would just remove the required status check once and for all. The purpose of it was to ensure that the deployed preview was reviewed before merging, but I don't think we really need that anymore.

**Pull request merged**
