### PR TITLE
Contributing policy

### PR DESCRIPTION
**Pull request by Mesure73L**

### CODE REVIEW

**Comment by Mesure73L** [comment]
@BeepBot99 what are your thoughts on the policy?

**Comment by BeepBot99** [comment]
Where can the new policy be viewed? It cannot be seen here.
image

**Comment by Mesure73L** [comment]
> Where can the new policy be viewed? It cannot be seen here.

Look it up, from what I read it does not appear in the overview but can be seen in issues and pull requests, and it can also be linked to like every other markdown file.

**Comment by BeepBot99** [comment]
I do not use the default settings in prettier. I set the max line width to 140 characters instead of 80 and I also changed some other stuff.
However, as long as you are using some version of prettier, it will be fine. That is because prettier does not offer many options. No matter what your settings are, it will always look roughly the same. So, I think it is fine how it is, but I am just letting you know about that.

**Comment by BeepBot99** [comment]
I do not use the default settings in prettier. I set the max line width to 140 characters instead of 80 and I also changed some other stuff.
However, as long as you are using some version of prettier, it will be fine. That is because prettier does not offer many options. No matter what your settings are, it will always look roughly the same. So, I think it is fine how it is, but I am just letting you know about that.

**Comment by Mesure73L** [comment]
> I do not use the default settings in prettier. I set the max line width to 140 characters instead of 80 and I also changed some other stuff.
> However, as long as you are using some version of prettier, it will be fine. That is because prettier does not offer many options. No matter what your settings are, it will always look roughly the same. So, I think it is fine how it is, but I am just letting you know about that.

"recommended"

**Comment by Mesure73L** [comment]
I never said anything about what you use

**Comment by BeepBot99** [comment]
Okay tell me when this is ready for reveiw.

**Comment by Mesure73L** [comment]
Actually, can you send me your full config?

**Comment by BeepBot99** [comment]
Just for Prettier or for all of VS Code?

**Comment by BeepBot99** [comment]
HAHA I CAN TALK IN THE SERVER IN WEBHOOKS EVEN WHEN I'M TIMED OUT

**Comment by BeepBot99** [comment]
Sure, here it is:
```json
{
    "editor.formatOnPaste": true,
    "editor.linkedEditing": true,
    "prettier.arrowParens": "avoid",
    "prettier.bracketSpacing": false,
    "prettier.bracketSameLine": true,
    "prettier.printWidth": 100,
    "prettier.tabWidth": 4,
    "prettier.trailingComma": "none",
    "prettier.quoteProps": "consistent",
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}

**Comment by Mesure73L** [comment]
> HAHA I CAN TALK IN THE SERVER IN WEBHOOKS EVEN WHEN I'M TIMED OUT

Please don't tho /srs

**Comment by BeepBot99** [comment]
> Please don't tho /srs

What do you mean though you just did.

**Comment by Mesure73L** [comment]
> > Please don't tho /srs
> 
> What do you mean though you just did.

I did to reply to you. Please stop after this.

**Comment by Mesure73L** [comment]
> Sure, here it is:
> 
> ```json
> {
>     "editor.formatOnPaste": true,
>     "editor.linkedEditing": true,
>     "prettier.arrowParens": "avoid",
>     "prettier.bracketSpacing": false,
>     "prettier.bracketSameLine": true,
>     "prettier.printWidth": 100,
>     "prettier.tabWidth": 4,
>     "prettier.trailingComma": "none",
>     "prettier.quoteProps": "consistent",
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
> }
> ```

How do I input that?

**Comment by Mesure73L** [comment]
I thought you would just tell me, but please answer it

**Comment by BeepBot99** [comment]
1. Do `ctrl` + `,` to get to settings. You can also click on settings in the bottom left corner and then click settings.
2. In the top right, click on the paper with an arrow. The tooltip says, "Open Settings (JSON)."
3. For each settings that I sent, change it to my value if it is already there, or add it to the end if it is not already there.

**Comment by BeepBot99** [comment]
Add https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github please.

**Comment by BeepBot99** [comment]
image
What is this?

**Comment by Mesure73L** [comment]
> Add https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github please.

Okay, I will.

> image
> What is this?

That is me merging the commit I made on GitHub to my GHCS clone. If you hover over it, it didn't interfere with any other branches at all.

**Comment by BeepBot99** [comment]
Oh right imagine being in school today. /t

**Comment by Mesure73L** [comment]
> Oh right imagine being in school today. /t

"DON'T SKIP SCHOOL EVER"
"Imagine skipping school today"
(both quotes from you)

**Comment by Mesure73L** [comment]
@BeepBot99 please review this

**Review by BeepBot99 — CHANGES_REQUESTED** [review]
The version on the Visual Studio Marketplace is an outdated version. The official name of the extension is "GitHub Pull Requests & Issues," please change it to that.

**Comment by Mesure73L** [comment]
then dont tell me to put the link on the list

**Comment by BeepBot99** [comment]
Okay fine I'll just do it myself then.

**Comment by BeepBot99** [comment]
Okay, I won't actually, because then I won't be able to review it, but can you please just change the name?

**Review by BeepBot99 — APPROVED** [review]
Looks good, merge when ready. Sorry for the complaints, I just wanted to make sure that the information is as accurate and up to date as possible!

**Pull request merged**
