### PR TITLE
Create auto-merge.yml

### PR DESCRIPTION
**Pull request by BeepBot99**
This automatically merges `main` into `develop` on pushes to `main`.
Make sure you also enable `Allow GitHub Actions to create and approve pull requests` under `Settings > Actions`.

### CODE REVIEW

**Comment by BeepBot99** [comment]
> I will review this by the end of the day.

Okay, but you don't need to. It is only 10 lines of code. By the way, this is what you need to do:
image
image

**Comment by Mesure73L** [comment]
> Okay, but you don't need to. It is only 10 lines of code.

Fine then, let me just create a PR that removes 10 variable definitions in Twelve of Code... using your own logic you won't need to review it.

**Comment by Mesure73L** [comment]
> Okay, but how can you review it? You don't even know actions syntax.

How do you know? (I'm friends with Google)

**Comment by Mesure73L** [comment]
By the way, make sure this **does not run** on pushes from `develop` into `main`.

**Review by Mesure73L — APPROVED** [review]
image
image

**Comment by BeepBot99** [comment]
> By the way, make sure this **does not run** on pushes from `develop` into `main`.

Oh right, I forgot about that.

**Comment by BeepBot99** [comment]
Done.

**Comment by BeepBot99** [comment]
Wait no this isn't done I thought this was another issue

**Comment by Mesure73L** [comment]
> Done.

Please move that to #105.

**Comment by Mesure73L** [comment]
I changed the setting btw

**Pull request merged**
